# To Run: conda env create -f environment.yml
name: musicautobot
channels:
- fastai
- pytorch
- conda-forge
- defaults
dependencies:
- pytorch
- fastai
- nbdev
- jupyter
- ipyparallel
- pip
- python=3.9
- cudatoolkit=11
- pip:
  - music21
  - pebble
#  - "--editable=git+https://github.com/fastai/fastai@master"
