# To Run: conda env create -f environment.yml
name: musicautobot_v1
channels:
- fastai
- pytorch
- defaults
dependencies:
- pytorch
#- fastai
- fastai=1.0.61
- nbdev
- jupyter
- ipyparallel
- pip
- python
- pip:
  - music21
  - pebble
#  - "--editable=git+https://github.com/fastai/fastai@master"
